using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Spartane.Core.Classes.StoredProcedure
{
   public class SpListSelAllPacientes : BaseEntity
    {
        public Int64 RowNumber { get; set; }
        public int Pacientes_Folio { get; set; }
        public DateTime? Pacientes_Fecha_de_Registro { get; set; }
        public string Pacientes_Hora_de_Registro { get; set; }
        public int? Pacientes_Usuario_que_Registra { get; set; }
        public string Pacientes_Usuario_que_Registra_Name { get; set; }
        public bool? Pacientes_Es_nuevo_registro { get; set; }
        public int? Pacientes_Tipo_de_Registro { get; set; }
        public string Pacientes_Tipo_de_Registro_Descripcion { get; set; }
        public int? Pacientes_Tipo_de_Paciente { get; set; }
        public string Pacientes_Tipo_de_Paciente_Descripcion { get; set; }
        public int? Pacientes_Usuario_Registrado { get; set; }
        public string Pacientes_Usuario_Registrado_Name { get; set; }
        public int? Pacientes_Empresa { get; set; }
        public string Pacientes_Empresa_Nombre_de_la_Empresa { get; set; }
        public string Pacientes_Numero_de_Empleado { get; set; }
        public string Pacientes_Nombres { get; set; }
        public string Pacientes_Apellido_Paterno { get; set; }
        public string Pacientes_Apellido_Materno { get; set; }
        public string Pacientes_Nombre_Completo { get; set; }
        public string Pacientes_Celular { get; set; }
        public string Pacientes_Email { get; set; }
        public DateTime? Pacientes_Fecha_de_nacimiento { get; set; }
        public string Pacientes_Nombre_del_Padre_o_Tutor { get; set; }
        public int? Pacientes_Pais_de_nacimiento { get; set; }
        public string Pacientes_Pais_de_nacimiento_Nombre_del_Pais { get; set; }
        public int? Pacientes_Lugar_de_nacimiento { get; set; }
        public string Pacientes_Lugar_de_nacimiento_Nombre_del_Estado { get; set; }
        public int? Pacientes_Sexo { get; set; }
        public string Pacientes_Sexo_Descripcion { get; set; }
        public int? Pacientes_Estado_Civil { get; set; }
        public string Pacientes_Estado_Civil_Descripcion { get; set; }
        public string Pacientes_Calle { get; set; }
        public string Pacientes_Numero_exterior { get; set; }
        public string Pacientes_Numero_interior { get; set; }
        public string Pacientes_Colonia { get; set; }
        public int? Pacientes_CP { get; set; }
        public string Pacientes_Ciudad { get; set; }
        public int? Pacientes_Pais { get; set; }
        public string Pacientes_Pais_Nombre_del_Pais { get; set; }
        public int? Pacientes_Estado { get; set; }
        public string Pacientes_Estado_Nombre_del_Estado { get; set; }
        public string Pacientes_Ocupacion { get; set; }
        public int? Pacientes_Cantidad_hijos { get; set; }
        public int? Pacientes_Objetivo { get; set; }
        public string Pacientes_Objetivo_Descripcion { get; set; }
        public int? Pacientes_Estatus_Paciente { get; set; }
        public string Pacientes_Estatus_Paciente_Descripcion { get; set; }
        public bool? Pacientes_Plan_Alimenticio_Completo { get; set; }
        public bool? Pacientes_Plan_Rutina_Completa { get; set; }
        public int? Pacientes_Cuenta_con_padecimientos { get; set; }
        public string Pacientes_Cuenta_con_padecimientos_Descripcion { get; set; }
        public int? Pacientes_Frecuencia_Cardiaca { get; set; }
        public int? Pacientes_Frecuencia_Respiratoria { get; set; }
        public int? Pacientes_Presion_sistolica { get; set; }
        public int? Pacientes_Presion_diastolica { get; set; }
        public decimal? Pacientes_Peso_actual { get; set; }
        public decimal? Pacientes_Estatura { get; set; }
        public decimal? Pacientes_Peso_habitual { get; set; }
        public int? Pacientes_Circunferencia_de_cintura_cm { get; set; }
        public int? Pacientes_Circunferencia_de_cadera_cm { get; set; }
        public int? Pacientes_Anchura_de_muneca_mm { get; set; }
        public int? Pacientes_Circunferencia_de_brazo_cm { get; set; }
        public int? Pacientes_Pliegue_cutaneo_tricipital_mm { get; set; }
        public int? Pacientes_Pliegue_cutaneo_bicipital_mm { get; set; }
        public int? Pacientes_Pliegue_cutaneo_subescapular_mm { get; set; }
        public int? Pacientes_Pliegue_cutaneo_supraespinal_mm { get; set; }
        public int? Pacientes_Edad_Metabolica { get; set; }
        public int? Pacientes_Agua_corporal { get; set; }
        public int? Pacientes_Grasa_Visceral { get; set; }
        public int? Pacientes_Grasa_Corporal { get; set; }
        public int? Pacientes_Grasa_Corporal_kg { get; set; }
        public int? Pacientes_Masa_Muscular_kg { get; set; }
        public int? Pacientes_Masa_Muscular_ { get; set; }
        public int? Pacientes_Esta_embarazada { get; set; }
        public string Pacientes_Esta_embarazada_Descripcion { get; set; }
        public int? Pacientes_Tu_embarazo_es_multiple { get; set; }
        public string Pacientes_Tu_embarazo_es_multiple_Descripcion { get; set; }
        public int? Pacientes_Semana_de_gestacion { get; set; }
        public int? Pacientes_Peso_pregestacional { get; set; }
        public int? Pacientes_Toma_anticonceptivos { get; set; }
        public string Pacientes_Toma_anticonceptivos_Descripcion { get; set; }
        public string Pacientes_Nombre_del_Anticonceptivo { get; set; }
        public string Pacientes_Dosis { get; set; }
        public int? Pacientes_Climaterio { get; set; }
        public string Pacientes_Climaterio_Descripcion { get; set; }
        public DateTime? Pacientes_Fecha_Climaterio { get; set; }
        public int? Pacientes_Terapia_reemplazo_hormonal { get; set; }
        public string Pacientes_Terapia_reemplazo_hormonal_Descripcion { get; set; }
        public int? Pacientes_Tipo_Dieta { get; set; }
        public string Pacientes_Tipo_Dieta_Descripcion { get; set; }
        public int? Pacientes_Suplementos { get; set; }
        public string Pacientes_Suplementos_Descripcion { get; set; }
        public int? Pacientes_Consumo_de_sal { get; set; }
        public string Pacientes_Consumo_de_sal_Descripcion { get; set; }
        public int? Pacientes_Grasas_Preferencias { get; set; }
        public string Pacientes_Grasas_Preferencias_Descripcion { get; set; }
        public int? Pacientes_Comidas_cantidad { get; set; }
        public string Pacientes_Comidas_cantidad_Descripcion { get; set; }
        public int? Pacientes_Preparacion_Preferencias { get; set; }
        public string Pacientes_Preparacion_Preferencias_Descripcion { get; set; }
        public int? Pacientes_Entre_comidas { get; set; }
        public string Pacientes_Entre_comidas_Descripcion { get; set; }
        public int? Pacientes_Apetito { get; set; }
        public string Pacientes_Apetito_Descripcion { get; set; }
        public int? Pacientes_Habitos_Modificacion { get; set; }
        public string Pacientes_Habitos_Modificacion_Descripcion { get; set; }
        public int? Pacientes_Horario_hambre { get; set; }
        public string Pacientes_Horario_hambre_Descripcion { get; set; }
        public int? Pacientes_Cuando_cambia_mi_estado_de_animo { get; set; }
        public string Pacientes_Cuando_cambia_mi_estado_de_animo_Descripcion { get; set; }
        public int? Pacientes_Medicamentos_bajar_peso { get; set; }
        public string Pacientes_Medicamentos_bajar_peso_Descripcion { get; set; }
        public string Pacientes_Cual_medicamento { get; set; }
        public int? Pacientes_Frecuencia_Ejercicio { get; set; }
        public string Pacientes_Frecuencia_Ejercicio_Descripcion { get; set; }
        public int? Pacientes_Duracion_Ejercicio { get; set; }
        public string Pacientes_Duracion_Ejercicio_Descripcion { get; set; }
        public int? Pacientes_Tipo_Ejercicio { get; set; }
        public string Pacientes_Tipo_Ejercicio_Descripcion { get; set; }
        public int? Pacientes_Antiguedad_Ejercicio { get; set; }
        public string Pacientes_Antiguedad_Ejercicio_Descripcion { get; set; }
        public int? Pacientes_IMC { get; set; }
        public int? Pacientes_Interpretacion_IMC { get; set; }
        public string Pacientes_Interpretacion_IMC_Descripcion { get; set; }
        public int? Pacientes_IMC_Pediatria { get; set; }
        public string Pacientes_IMC_Pediatria_Descripcion { get; set; }
        public string Pacientes_Complexion_corporal { get; set; }
        public int? Pacientes_Interpretacion_complexion_corporal { get; set; }
        public string Pacientes_Interpretacion_complexion_corporal_Descripcion { get; set; }
        public string Pacientes_Distribucion_de_grasa_corporal { get; set; }
        public int? Pacientes_Interpretacion_grasa_corporal { get; set; }
        public string Pacientes_Interpretacion_grasa_corporal_Descripcion { get; set; }
        public string Pacientes_Indice_cintura_cadera { get; set; }
        public int? Pacientes_Interpretacion_indice { get; set; }
        public string Pacientes_Interpretacion_indice_Descripcion { get; set; }
        public string Pacientes_Consumo_de_agua_resultado { get; set; }
        public int? Pacientes_Interpretacion_agua { get; set; }
        public string Pacientes_Interpretacion_agua_Descripcion { get; set; }
        public int? Pacientes_Frecuencia_cardiaca_en_Esfuerzo { get; set; }
        public int? Pacientes_Interpretacion_frecuencia { get; set; }
        public string Pacientes_Interpretacion_frecuencia_Descripcion { get; set; }
        public int? Pacientes_Dificultad_de_Rutina_de_Ejercicios { get; set; }
        public string Pacientes_Dificultad_de_Rutina_de_Ejercicios_Dificultad { get; set; }
        public int? Pacientes_Interpretacion_dificultad { get; set; }
        public string Pacientes_Interpretacion_dificultad_Descripcion { get; set; }
        public int? Pacientes_Calorias { get; set; }
        public int? Pacientes_Interpretacion_calorias { get; set; }
        public string Pacientes_Interpretacion_calorias_Descripcion { get; set; }
        public string Pacientes_Observaciones { get; set; }

    }
}
