using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Spartane.Core.Classes.StoredProcedure
{
    public class Sp_SelallPacientes_Complete : BaseEntity
    {
        public int Folio { get; set; }
        public DateTime? Fecha_de_Registro { get; set; }
        public string Hora_de_Registro { get; set; }
        public int? Usuario_que_Registra { get; set; }
        public string Usuario_que_Registra_Name { get; set; }
        public bool? Es_nuevo_registro { get; set; }
        public int? Tipo_de_Registro { get; set; }
        public string Tipo_de_Registro_Descripcion { get; set; }
        public int? Tipo_de_Paciente { get; set; }
        public string Tipo_de_Paciente_Descripcion { get; set; }
        public int? Usuario_Registrado { get; set; }
        public string Usuario_Registrado_Name { get; set; }
        public int? Empresa { get; set; }
        public string Empresa_Nombre_de_la_Empresa { get; set; }
        public string Numero_de_Empleado { get; set; }
        public string Nombres { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Nombre_Completo { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public DateTime? Fecha_de_nacimiento { get; set; }
        public string Nombre_del_Padre_o_Tutor { get; set; }
        public int? Pais_de_nacimiento { get; set; }
        public string Pais_de_nacimiento_Nombre_del_Pais { get; set; }
        public int? Lugar_de_nacimiento { get; set; }
        public string Lugar_de_nacimiento_Nombre_del_Estado { get; set; }
        public int? Sexo { get; set; }
        public string Sexo_Descripcion { get; set; }
        public int? Estado_Civil { get; set; }
        public string Estado_Civil_Descripcion { get; set; }
        public string Calle { get; set; }
        public string Numero_exterior { get; set; }
        public string Numero_interior { get; set; }
        public string Colonia { get; set; }
        public int? CP { get; set; }
        public string Ciudad { get; set; }
        public int? Pais { get; set; }
        public string Pais_Nombre_del_Pais { get; set; }
        public int? Estado { get; set; }
        public string Estado_Nombre_del_Estado { get; set; }
        public string Ocupacion { get; set; }
        public int? Cantidad_hijos { get; set; }
        public int? Objetivo { get; set; }
        public string Objetivo_Descripcion { get; set; }
        public int? Estatus_Paciente { get; set; }
        public string Estatus_Paciente_Descripcion { get; set; }
        public bool? Plan_Alimenticio_Completo { get; set; }
        public bool? Plan_Rutina_Completa { get; set; }
        public int? Cuenta_con_padecimientos { get; set; }
        public string Cuenta_con_padecimientos_Descripcion { get; set; }
        public int? Frecuencia_Cardiaca { get; set; }
        public int? Frecuencia_Respiratoria { get; set; }
        public int? Presion_sistolica { get; set; }
        public int? Presion_diastolica { get; set; }
        public decimal? Peso_actual { get; set; }
        public decimal? Estatura { get; set; }
        public decimal? Peso_habitual { get; set; }
        public int? Circunferencia_de_cintura_cm { get; set; }
        public int? Circunferencia_de_cadera_cm { get; set; }
        public int? Anchura_de_muneca_mm { get; set; }
        public int? Circunferencia_de_brazo_cm { get; set; }
        public int? Pliegue_cutaneo_tricipital_mm { get; set; }
        public int? Pliegue_cutaneo_bicipital_mm { get; set; }
        public int? Pliegue_cutaneo_subescapular_mm { get; set; }
        public int? Pliegue_cutaneo_supraespinal_mm { get; set; }
        public int? Edad_Metabolica { get; set; }
        public int? Agua_corporal { get; set; }
        public int? Grasa_Visceral { get; set; }
        public int? Grasa_Corporal { get; set; }
        public int? Grasa_Corporal_kg { get; set; }
        public int? Masa_Muscular_kg { get; set; }
        public int? Masa_Muscular_ { get; set; }
        public int? Esta_embarazada { get; set; }
        public string Esta_embarazada_Descripcion { get; set; }
        public int? Tu_embarazo_es_multiple { get; set; }
        public string Tu_embarazo_es_multiple_Descripcion { get; set; }
        public int? Semana_de_gestacion { get; set; }
        public int? Peso_pregestacional { get; set; }
        public int? Toma_anticonceptivos { get; set; }
        public string Toma_anticonceptivos_Descripcion { get; set; }
        public string Nombre_del_Anticonceptivo { get; set; }
        public string Dosis { get; set; }
        public int? Climaterio { get; set; }
        public string Climaterio_Descripcion { get; set; }
        public DateTime? Fecha_Climaterio { get; set; }
        public int? Terapia_reemplazo_hormonal { get; set; }
        public string Terapia_reemplazo_hormonal_Descripcion { get; set; }
        public int? Tipo_Dieta { get; set; }
        public string Tipo_Dieta_Descripcion { get; set; }
        public int? Suplementos { get; set; }
        public string Suplementos_Descripcion { get; set; }
        public int? Consumo_de_sal { get; set; }
        public string Consumo_de_sal_Descripcion { get; set; }
        public int? Grasas_Preferencias { get; set; }
        public string Grasas_Preferencias_Descripcion { get; set; }
        public int? Comidas_cantidad { get; set; }
        public string Comidas_cantidad_Descripcion { get; set; }
        public int? Preparacion_Preferencias { get; set; }
        public string Preparacion_Preferencias_Descripcion { get; set; }
        public int? Entre_comidas { get; set; }
        public string Entre_comidas_Descripcion { get; set; }
        public int? Apetito { get; set; }
        public string Apetito_Descripcion { get; set; }
        public int? Habitos_Modificacion { get; set; }
        public string Habitos_Modificacion_Descripcion { get; set; }
        public int? Horario_hambre { get; set; }
        public string Horario_hambre_Descripcion { get; set; }
        public int? Cuando_cambia_mi_estado_de_animo { get; set; }
        public string Cuando_cambia_mi_estado_de_animo_Descripcion { get; set; }
        public int? Medicamentos_bajar_peso { get; set; }
        public string Medicamentos_bajar_peso_Descripcion { get; set; }
        public string Cual_medicamento { get; set; }
        public int? Frecuencia_Ejercicio { get; set; }
        public string Frecuencia_Ejercicio_Descripcion { get; set; }
        public int? Duracion_Ejercicio { get; set; }
        public string Duracion_Ejercicio_Descripcion { get; set; }
        public int? Tipo_Ejercicio { get; set; }
        public string Tipo_Ejercicio_Descripcion { get; set; }
        public int? Antiguedad_Ejercicio { get; set; }
        public string Antiguedad_Ejercicio_Descripcion { get; set; }
        public int? IMC { get; set; }
        public int? Interpretacion_IMC { get; set; }
        public string Interpretacion_IMC_Descripcion { get; set; }
        public int? IMC_Pediatria { get; set; }
        public string IMC_Pediatria_Descripcion { get; set; }
        public string Complexion_corporal { get; set; }
        public int? Interpretacion_complexion_corporal { get; set; }
        public string Interpretacion_complexion_corporal_Descripcion { get; set; }
        public string Distribucion_de_grasa_corporal { get; set; }
        public int? Interpretacion_grasa_corporal { get; set; }
        public string Interpretacion_grasa_corporal_Descripcion { get; set; }
        public string Indice_cintura_cadera { get; set; }
        public int? Interpretacion_indice { get; set; }
        public string Interpretacion_indice_Descripcion { get; set; }
        public string Consumo_de_agua_resultado { get; set; }
        public int? Interpretacion_agua { get; set; }
        public string Interpretacion_agua_Descripcion { get; set; }
        public int? Frecuencia_cardiaca_en_Esfuerzo { get; set; }
        public int? Interpretacion_frecuencia { get; set; }
        public string Interpretacion_frecuencia_Descripcion { get; set; }
        public int? Dificultad_de_Rutina_de_Ejercicios { get; set; }
        public string Dificultad_de_Rutina_de_Ejercicios_Dificultad { get; set; }
        public int? Interpretacion_dificultad { get; set; }
        public string Interpretacion_dificultad_Descripcion { get; set; }
        public int? Calorias { get; set; }
        public int? Interpretacion_calorias { get; set; }
        public string Interpretacion_calorias_Descripcion { get; set; }
        public string Observaciones { get; set; }

    }
}
