$(document).ready(function () {
    var inpuElementArray = [{"inputId":"WorkFlowId","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Name","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Description","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Objective","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Status","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Object","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null}];
    setInputEntityAttributes(inpuElementArray, "#", 1);
});


  
 function setSpartan_WorkFlow_PhasesValidation() {  
 var inpuElementChildArray =[{"inputId":"XXX","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"Default","HelpText":""},{"inputId":"Phase_Number","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Name","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Phase_Type","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Type_of_Work_Distribution","inputType":"select","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Type_Flow_Control","inputType":"select","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Phase_Status","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""}];  
 setInputEntityAttributes(inpuElementChildArray, ".", 0);  
 setDynamicRenderElement(); 
 } 
  
 function setSpartan_WorkFlow_StateValidation() {  
 var inpuElementChildArray =[{"inputId":"XXX","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"Default","HelpText":""},{"inputId":"Phase","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Attribute","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"State_Code","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Name","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Value","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Text","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""}];  
 setInputEntityAttributes(inpuElementChildArray, ".", 0);  
 setDynamicRenderElement(); 
 } 
  
 function setSpartan_WorkFlow_Conditions_by_StateValidation() {  
 var inpuElementChildArray =[{"inputId":"XXX","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"Default","HelpText":""},{"inputId":"Phase","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"State","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Condition_Operator","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Attribute","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Condition","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Operator","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Operator_Value","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Priority","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""}];  
 setInputEntityAttributes(inpuElementChildArray, ".", 0);  
 setDynamicRenderElement(); 
 } 
  
 function setSpartan_WorkFlow_Information_by_StateValidation() {  
 var inpuElementChildArray =[{"inputId":"XXX","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"Default","HelpText":""},{"inputId":"Phase","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"State","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Folder","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Visible","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Read_Only","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Required","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Label","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""}];  
 setInputEntityAttributes(inpuElementChildArray, ".", 0);  
 setDynamicRenderElement(); 
 } 
  
 function setSpartan_WorkFlow_Roles_by_StateValidation() {  
 var inpuElementChildArray =[{"inputId":"XXX","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"Default","HelpText":""},{"inputId":"Phase","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"State","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"User_Role","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Phase_Transition","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Permission_To_Consult","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Permission_To_New","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Permission_To_Modify","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Permission_to_Delete","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Permission_To_Export","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Permission_To_Print","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""},{"inputId":"Permission_Settings","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"","HelpText":""}];  
 setInputEntityAttributes(inpuElementChildArray, ".", 0);  
 setDynamicRenderElement(); 
 } 
  
 function setSpartan_WorkFlow_Matrix_of_StatesValidation() {  
 var inpuElementChildArray =[{"inputId":"XXX","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":"Default","HelpText":null},{"inputId":"Phase","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"State","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"Attribute","inputType":"select","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"Visible","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"Required","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"Read_Only","inputType":"checkbox","IsRequired":false,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"Label","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"Default_Value","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null},{"inputId":"Help_Text","inputType":"text","IsRequired":true,"IsVisible":true,"IsReadOnly":false,"DefaultValue":null,"HelpText":null}];  
 setInputEntityAttributes(inpuElementChildArray, ".", 0);  
 setDynamicRenderElement(); 
 } 
